# ============================================================================================================
# Set on Listening
# Port to listen on (non-privileged ports are > 1023)
# ============================================================================================================
port=5050
# ============================================================================================================
# Setting database for all client (HOST 127.0.0.1 only)
# ============================================================================================================
host=127.0.0.1
user=alltra
password=rHCBGz4BnmYw@
name_db=agents
# ============================================================================================================
# Set path on file from client directory 
# ============================================================================================================
path_file=/Users/kuzan04/Documents/workSpace/project_sgc/file_server/
ftp_owner=kuzan04
ftp_group=staff
# ============================================================================================================
# Column ID or Columns at AUTO_INCREMENT not config AND but datetime, timestamp = CURRENTY_TIMESTAMP not config
# Table here for client logs hash0
# ============================================================================================================
table=hash:device_name, os_name, path, name_file, total_line, value
# ============================================================================================================
# Table here client directory/file *NOTE* must have column ID!!
# ============================================================================================================
table=dir_device:id, device_name, os_name, path, name_file
# ============================================================================================================
# Table here client check database *NOTE* must have column ID!!
# ============================================================================================================
table=checkdb_server:id, status
# ============================================================================================================
# Setup to create a self signed X509 certificate
# ============================================================================================================
email=kittiphum1230@hotmail.co.th
commonname=agentListen
countryName=TH
localityName=ChiangRai
stateOrProvinceName=Muang
organizationName=Alltra
organizationUnitName=Enterprise
# ============================================================================================================
