# ============================================================================================================
# Set on Listening
# Port to listen on (non-privileged ports are > 1023)
# ============================================================================================================================================
port=5050
# ============================================================================================================================================
# Setting database for all client (HOST 127.0.0.1 only)
# ============================================================================================================================================
host=127.0.0.1
user=alltra
password=rHCBGz4BnmYw@
name_db=DOL_PDPA_LOCAL
# ============================================================================================================================================
# Set path on file from client directory 
# ============================================================================================================================================
sourcination=/Users/kuzan04/Documents/workSpace/project_sgc/file_server/
destination_log=/var/log/agent/
destination_doc=/var/pdpa/agent/
# ============================================================================================================================================
# Column ID or Columns at AUTO_INCREMENT not config AND but datetime, timestamp = CURRENTY_TIMESTAMP not config
# Table here for client logs hash0
# ============================================================================================================================================
table=TB_TR_PDPA_AGENT_LOG0_HASH:device_name, os_name, path, name_file, total_line, value, value_md5, value_sha1
# ============================================================================================================================================
# Table here client directory/file *NOTE* must have column ID!!
# ============================================================================================================================================
table=TB_TR_PDPA_AGENT_FILE_DIR:id, device_name, os_name, path, name_file, size
# ============================================================================================================================================
# Table here client check database *NOTE* must have column ID!!
# ============================================================================================================================================
table=TB_TR_PDPA_AGENT_DATABASE_CHECK:field_1, field_2, field_3, field_4, field_5, field_6, field_7, field_8, field_9, field_0, from_client
# ============================================================================================================================================
# Save history log
# ============================================================================================================================================
table=TB_TR_PDPA_AGENT_LISTEN_HISTORY:agm_id
# ============================================================================================================================================
# Setup to create a self signed X509 certificate
# ============================================================================================================================================
email=kittiphum1230@hotmail.co.th
commonname=agentListen
countryName=TH
localityName=ChiangRai
stateOrProvinceName=Muang
organizationName=Alltra
organizationUnitName=Enterprise
# ============================================================================================================================================
